server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/WordAPI
    username: postgres
    password: root
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/WordAPI
    user: postgres
    password: root
  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keyLength: 256
  token:
    secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
    expired: 3600000

debug: true

nazariiboiko:
  openapi:
    dev-url: http://localhost:8086
    prod-url: